import { images } from ".";

export const ProductsItems_img = [
  {
    id: 1,
    productImage: images.ProductsItems_img_brownies_hazelnut,
    productName: "Hazelnut Fudge",
    pricedescription: "Piece",
    price: 35,
  },
  {
    id: 2,
    productImage: images.ProductsItems_img_brownies_minou,
    productName: "Minou's Brownies",
    pricedescription: "Box of 6 pieces",
    price: 240,
  },
  {
    id: 3,
    productImage: images.ProductsItems_img_brownies_oreos,
    productName: "Oreos Brownies",
    pricedescription: "Box of 6 pieces",
    price: 210,
  },
  {
    id: 4,
    productImage: images.ProductsItems_img_cookies_chocolate_ships_6_pics,
    productName: "Chocolate Chips Cookies",
    productDescription: "( Milk & Dark Chocolate Chips )",
    pricedescription: "Box of 6 pieces",
    price: 75,
  },
  {
    id: 5,
    productImage: images.ProductsItems_img_cookies_chocolate_ships_12_pics,
    productName: "Chocolate Chips Cookies",
    productDescription: "( Milk & Dark Chocolate Chips )",
    pricedescription: "Box of 12 pieces",
    price: 120,
  },
  {
    id: 6,
    productImage: images.ProductsItems_img_cookies_chocolate_ships_24_pics,
    productName: "Chocolate Chips Cookies",
    productDescription: "( Milk & Dark Chocolate Chips )",
    pricedescription: "Box of 24 pieces",
    price: 200,
  },
  {
    id: 7,
    productImage: images.ProductsItems_img_summer_cookies_12_pics,
    productName: "Summer Cookies",
    productDescription: "( Topped with royal icing )",
    pricedescription: "Box of 12 pieces",
    price: 180,
  },
  {
    id: 8,
    productImage: images.ProductsItems_img_summer_cookies_25_pics,
    productName: "Summer Cookies",
    productDescription: "( Topped with royal icing )",
    pricedescription: "Box of 25 pieces",
    price: 375,
  },
  {
    id: 9,
    productImage: images.ProductsItems_img_cookies_oatmeal,
    productName: "Healthy Oatmeal raisin Bites",
    productDescription: "( includes nuts & a mix spices )",
    pricedescription: "Box of 10 pieces",
    price: 100,
  },
  {
    id: 10,
    productImage: images.ProductsItems_img_cupcakes_vanlia,
    productName: "Vanilla Cupcakes",
    productDescription: "( Filled with homeemade strawberry jam )",
    pricedescription: "Box of 5 pieces",
    price: 150,
  },
  {
    id: 11,
    productImage: images.ProductsItems_img_cupcakes_chocolate,
    productName: "Chocolate Cupcakes",
    productDescription: "( With toasted marshmallows )",
    pricedescription: "Box of 5 pieces",
    price: 120,
  },
  {
    id: 12,
    productImage: images.ProductsItems_img_cupcakes_summer,
    productName: "Summer Cupcakes",
    productDescription: "( With refreshing lemon flavor )",
    pricedescription: "Box of 5 pieces",
    price: 150,
  },
  {
    id: 13,
    productImage: images.ProductsItems_img_eclairs_salted,
    productName: "Éclair ",
    productDescription: "( Salted / Nutty Caramel )",
    pricedescription: "Box of 5 pieces",
    price: 125,
  },
  {
    id: 14,
    productImage: images.ProductsItems_img_eclairs_coffee,
    productName: "Éclair ",
    productDescription: "( Coffe Cream )",
    pricedescription: "Box of 5 pieces",
    price: 125,
  },
  {
    id: 15,
    productImage: images.ProductsItems_img_eclairs_lemon,
    productName: "Éclair ",
    productDescription: "( Lemon And White Chocolate )",
    pricedescription: "Box of 5 pieces",
    price: 125,
  },
];
